### ISSUE TITLE
🛣 Road to Ferdi 5.6.0

### ISSUE THREAD

**Issue by vantezzen** [getferdi/ferdi#1017]
As suggested by @kytwb on Gitter, we should start planning the release of 5.6.0. Ferdi's last stable release was 5.5.0, released almost half a year ago.

# Todo before release
- [x] Release a new beta and make sure the build chain work now
- [x] Merge #977
- [x] Merge #567
- [x] Merge Franz 5.6.0?
        We will need to make sure our Ferdi Todos feature still works as Franz 5.6.0 made some large changes to that.
- [x] I don't think we will be able to support extensions in this update - that PR is now nearly ready yet
- [x] Fix any critical bugs that may appear in the new beta

# Todo during release
- [x] Update changelog
- [x] Binary testing
- [ ] Schedule tweet and instagram post, maybe ProductHunt release?
- [ ] Update Announcement API
- [x] Update casks
- [x] Update website

**Comment by LongJohn-Silver** [comment]
Is there a way in which I can update to beta on flatpak without installing two versions? So I can send reports through that if necessary.

**Comment by beppe9000** [comment]
What are the steps to build the exe from develop branch? Is there a CI from it?

**Comment by vantezzen** [comment]
@beppe9000 You can find our tutorial on how to develop and build Ferdi at https://github.com/getferdi/ferdi#development

**Comment by beppe9000** [comment]
it does not tell how to make the setup.exe

**Comment by kytwb** [comment]
@beppe9000 you want to run the [packaging](https://github.com/getferdi/ferdi#packaging) command, the `.exe` will be in the `./out`folder.

**Comment by beppe9000** [comment]
Ok, so it was me... _deliverables_ is a bit vague, tho...

**Comment by kytwb** [comment]
@beppe9000 no problem, iterated on it 👌

**Comment by beppe9000** [comment]
perfect thanks!

**Comment by vantezzen** [comment]
@kytwb What do you think about publishing the last beta today? As far as I can tell, #1033 still needs a bit of time and we might be better off just releasing 5.6 with all its new features and releasing 5.7 with Franz 5.6 merged and (hopefully) extension support in the next few months.

**Comment by vossmedien** [comment]
So... :-) Are you still working on it? Thank you mate.

**Comment by Stanzilla** [comment]
Franz 5.6.0 final is out now

**Comment by LongJohn-Silver** [comment]
@Stanzilla I checked the releases and there's nothing new, updated my system, nothing, checked Flathub, nothing, checked the pull requests and there's also nothing new. Where did you get it was releases?

**Comment by Stanzilla** [comment]
@LongJohn-Silver https://github.com/meetfranz/franz/releases/tag/v5.6.0

**Comment by vantezzen** [comment]
@Stanzilla Thanks for letting us know! I updated the description to merge Franz 5.6.0 final

**Comment by kytwb** [comment]
@vantezzen I'd say go ahead and give it another try if you have time!

The most important part is to make sure all the assets are uploaded before hitting the publish button for the release. Before hitting the publish button, the assets count at the time of writing should be 13. When publishing the release, there will be 2 assets added by GitHub (archives of the source code), bringing up the release assets count to 15.

**Comment by vantezzen** [comment]
@kytwb So the jobs ran through, the Mac build errored with this message though:

```
Error: Command failed: codesign
code object is not signed at all
```

Are the Apple Credentials etc. still valid?

Also, none of the assets seem to get uploaded to GitHub - the release is still empty

<img width="586" alt="Screenshot 2020-11-19 at 10 04 34" src="https://user-images.githubusercontent.com/10333196/99644782-a3de4280-2a4e-11eb-8a59-7380416ed461.png">

**Comment by adir6** [comment]
Hi, I have a little suggestion over here if you don't mind. Please if you could make the Proxy Support for the Ferdi better? Because, Proxy Details are lost from the Ferdi very often and I am required to add the details again and again.

Secondly, if you could make a better Proxy Management. So I would add the Proxy once in the Ferdi and then I can simply select the apps where I wish to use the Proxy.

This way, I won't have to add the Proxy to the apps again and again.

Thanks.

**Comment by vantezzen** [comment]
@adir6 Enhancing Proxy support is already being discussed over at #587

**Comment by adir6** [comment]
> @adir6 Enhancing Proxy support is already being discussed over at #587

That has been marked stale.

**Comment by vraravam** [comment]
Is there any movement on this? One of the reasons I switched to Ferdi is for the active development - which purpose is defeated if we lag so far behind Franz.

**Comment by LongJohn-Silver** [comment]
@vraravam Although I share your feelings since Ferdi's update is one of the software I have been waiting for too long, it would be nice to understand the developers position here. Ferdi is basicalñy a web browser of sort, which requires a ton of work, and to be honest their team is not big, but the contrary. It would be awesome if people would not demand so much and try to help.

**Comment by vraravam** [comment]
@LongJohn-Silver - to reciprocate the sentiment, i do try to help by both testing and have submitted a couple of patches/fixes in the recent past. But, as a user, the need to wait for such a long time is still intriguing.

> @Stanzilla Thanks for letting us know! I updated the description to merge Franz 5.6.0 final.
> 
> I'd publish a new Ferdi beta for testing but the last 2 times I've done that something in the build chain broke 😅

The above comment is 26 days old at this point. I am running the nighly (5.6.0-nightly.11.2657) without any issues since it was released. Any other way in which I/we can help?

**Comment by vantezzen** [comment]
@vraravam I am currently waiting for @kytwb to give an update on the signing keys for Apple.

I tried creating a new beta in order to prepare for the 5.6 release but the build/upload chain seems to be broken as no release artifacts are uploaded by the CI:

<img width="446" alt="Screenshot 2020-12-11 at 13 43 51" src="https://user-images.githubusercontent.com/10333196/101904922-e959df80-3bb6-11eb-9dad-bfc1f060d8ff.png">

**Comment by vraravam** [comment]
thanks @vantezzen . I guess we will have to wait for @kytwb

**Comment by endiz** [comment]
Is it possible to omit the Apple release and publish the other platform betas?

**Comment by beppe9000** [comment]
I think it would make sense to put that on hold

**Comment by vantezzen** [comment]
@endiz Yes, that could be a good idea. Unfortunately, it looks like the upload chain is broken, too. As I said, I tried to create a new beta a few weeks ago and the Linux and Windows build finished successfully, but there are still no assets in the GitHub release - even though they should be there.

We have made some changes to the build configurations since the last release and it looks like that broke some stuff. Unfortunately, I don't really know much about how to configure them - @kytwb did pretty much all of that. So if any of you have experience with TravisCI and AppVeyor configurations, feel free to take a look at the configurations in this repo and see if you find anything wring with them.

Here are the builds of the release I've created:
Travis: https://travis-ci.org/github/getferdi/ferdi/jobs/744182386
AppVeyor: https://ci.appveyor.com/project/kytwb/ferdi/builds/36357891

**Comment by vantezzen** [comment]
After reading a bit about how to set up the CI configs, I finally managed to release a new beta version 🥳

https://github.com/getferdi/ferdi/releases/tag/v5.6.0-beta.4

**Comment by adir6** [comment]
Hello, I wish to remind the important of better proxy management.

https://github.com/getferdi/ferdi/issues/1121

https://github.com/getferdi/ferdi/issues/587

**Comment by vantezzen** [comment]
@adir6 We, the Ferdi core team, are not currently working on improving proxy management as we don't use it ourselves.

Ferdi is an open-source project and as you might have seen from our changelogs, a lot of the features and bug fixes in Ferdi come from our community. So if you feel like Proxy Management is an important feature that should be improved, feel free to dive into Ferdi's code and implement the improvements - we will be happy to merge your PR into our repo!

**Comment by adir6** [comment]
> @adir6 We, the Ferdi core team, are not currently working on improving proxy management as we don't use it ourselves.
> 
> Ferdi is an open-source project and as you might have seen from our changelogs, a lot of the features and bug fixes in Ferdi come from our community. So if you feel like Proxy Management is an important feature that should be improved, feel free to dive into Ferdi's code and implement the improvements - we will be happy to merge your PR into our repo!

Appreciate you reply. I personally wish I could fix the issue for myself, but I don't know coding. Hmm, I wish if someone of you could try to fix the issue because, a lot of applications are blocked in my country and hence that makes it important for me to use Proxy with them. I don't want to use desktop-wide VPNs because that makes issues sometimes with Authentication at various Banks and Social Websites.

But, I do understand that, it's open source project and should be done in community efforts. I wish I could help myself and community in this case.

**Comment by k3tan172** [comment]
Can anyone confirm 5.6.0-Beta.5 Twitter service does not work?

**Comment by RaphaelJenni** [comment]
With the latest beta I cannot sign in to gmail as "the browser or app might be not secure".

**Comment by k3tan172** [comment]
> With the latest beta I cannot sign in to gmail as "the browser or app might be not secure".
> 
> **https://stackoverflow.com/questions/59685927/electron-application-using-google-oauth-this-browser-or-app-may-not-be-secure**

This can be fixed. Go to edit > open user.js.
It'll open up a folder. In the folder replace the user.js with
```
"use strict";

module.exports = Franz => class Messenger extends Franz {
  overrideUserAgent() {
    return "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36";
  }
};
```

Reload service. Should be able to log in.

**Comment by vraravam** [comment]
With the latest bet, I'm unable to use Whatsapp web

**Comment by DeEmilio** [comment]
I may be in the minority here, but I really liked popup windows in 5.6.0-beta.2 instead of opening links in external browser like it is in 5.6.0-Beta.5. Is it possible to include this switch in the settings for user to choose whether to open links directly in external browser or using integrated browser?

**Comment by RaphaelJenni** [comment]
> > With the latest beta I cannot sign in to gmail as "the browser or app might be not secure".
> > **https://stackoverflow.com/questions/59685927/electron-application-using-google-oauth-this-browser-or-app-may-not-be-secure**
> 
> This can be fixed. Go to edit > open user.js.
> It'll open up a folder. In the folder replace the user.js with
> 
> ```
> "use strict";
> 
> module.exports = Franz => class Messenger extends Franz {
>   overrideUserAgent() {
>     return "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36";
>   }
> };
> ```
> 
> Reload service. Should be able to log in.

Thanks, but sadly that doesn't work.

**Comment by vraravam** [comment]
In an existing installation (ie where the ferdi profile + preferences are already present on the local machine), when I upgrade to the latest beta (5), any service other than the first 10 do NOT show up on the left nav bar. Adding a new service (I tried with "zoho mail") doesn't work. I had to downgrade to the older nightly/beta versions for these to work. Also, at this time, WhatsApp has stopped working - prompting for a Chrome upgrade.

**Comment by mycanaletto** [comment]
I upgraded to the latest beta version, everything seems to work, except the corector where it remains desperately in English... I had already seen this problem on other versions and I don't think it's related to this beta. Welcome ideas...

**Comment by vraravam** [comment]
One more issue that I noticed: I keep getting a notification (pink color bar on the bottom of the Ferdi window) stating that my services have been updated, and prompting me to "Reload Services". This is happening with the new beta almost every few mins.

**Comment by geovannimp** [comment]
I have the problem with "Reload Services" at 5.6.0-beta.5 version too.

**Comment by vraravam** [comment]
So, is there any traction in releasing the public version?

**Comment by kytwb** [comment]
I just merged #1033 so the latest updates are available on `develop` and in the next nightly releases.  

From the pull request, remained:

- [ ]   Make Franz hibernation implementation work with preferred hibernation timeout set in Ferdi settings
- [ ] Review context menu to add missing Franz entries (save image, go back, go forward, ...)
- [ ] Review isTodosServiceActive / TODOS_RECIPE_ID logic to make it work with multiple TODOS services

If anyone wants to pull the latest changes and give a look at any of the above, or other regressions possibly introduced by #1033, your help is appreciated.

**Comment by vraravam** [comment]
@kytwb - I was not successful in building from source, but if a new nightly is released, I can offer to run through the services that I have for testing purposes.

**Comment by kris7t** [comment]
@kytwb There seems to be a problem with dependencies. I'm building on Linux and get

```
Error: ENOENT: no such file or directory, open '/usr/lib/ferdi/app.asar.unpacked/node_modules/mac-screen-capture-permissions/package.json'
    at Object.openSync (fs.js:440:3)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.readFileSync (fs.js:342:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at Object.internalBinding.internalModuleReadJSON (electron/js2c/asar.js:664:19)
    at readPackage (internal/modules/cjs/loader.js:231:34)
    at readPackageMain (internal/modules/cjs/loader.js:277:15)
    at tryPackage (internal/modules/cjs/loader.js:287:15)
    at Function.Module._findPath (internal/modules/cjs/loader.js:532:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:784:27)
```

after installation. Maybe the dependency on `mac-screen-capture-permissions` should be conditional on running on a Mac (I'm on Arch Linux)?

**Comment by PeterCxy** [comment]
@kris7t The problem is in the AUR `PKGBUILD` file -- it only copies the `recipes` directory in `app.asar.unpacked` and nothing else, but the latest develop branch has more than just that one single directory (see `electron-builder.yml`). Just fix the `PKGBUILD` by adding all the new sub-directories and it will work fine.

**Comment by phirsch** [comment]
> Can anyone confirm 5.6.0-Beta.5 Twitter service does not work?

FWIW: DevTools network panel shows update requests being issued (and replies coming in) every few seconds, but all I see is a blank page with no indication of any activity at all.

**Comment by gautamsi** [comment]
we should definitely upgrade electron version. Teams is giving issue in production version, probably due to Chromium engine is not supported any more.

**Comment by mastercko** [comment]
Agreed, please do!

**Comment by vraravam** [comment]
Is there any movement on this?

**Comment by vraravam** [comment]
@kytwb - any updates on this please?

**Comment by justus-saul** [comment]
> @kytwb - any updates on this please?

Sadly I think we have to assume ferdi to be dead

**Comment by kytwb** [comment]
@justus-saul I beg to differ:

![Screen Shot 2021-03-24 at 9 28 11 AM](https://user-images.githubusercontent.com/412895/112278564-44ee3b80-8c83-11eb-93dc-3d19a226ff6b.png)

Can you help with https://github.com/getferdi/ferdi/issues/1017#issuecomment-775014033?

**Comment by vraravam** [comment]
Can someone please release a new nightly version? @kytwb ?

**Comment by kytwb** [comment]
@vraravam I followed-up in https://github.com/getferdi/ferdi/issues/1254#issuecomment-805784334

**Comment by vraravam** [comment]
@kytwb - any updates on this please?

**Comment by vraravam** [comment]
We have finally gotten the nighlies back on track. Please download the [latest nightly](https://github.com/getferdi/nightlies/releases) and report back any errors. If your previous comments talked about issues, and these are now fixed, please do quote them and say "fixed" - that way, we will be able to proceed for the 5.6.0 GA release.

**Comment by vraravam** [comment]
In-app updater is now fixed in #1479 - but, the _first download_ will still have to be downloaded and installed _manually_ and the auto-updater should get fixed after that point onwards. Please wait for the next nightly release v56) over [here](https://github.com/getferdi/nightlies/releases)

**Comment by vraravam** [comment]
For those following this thread: Please try with the nightly builds from [here](http://github.com/vraravam/nightlies/releases) - this exposes the ability to the user to control the user-agent via the UI as opposed to editing files in the Ferdi profile. Please do be aware of the **unsigned nature** of the builds in this repo - while we work on fixing the issue with signing of our build artifacts.

**Comment by MurzNN** [comment]
Can we bump Electron to 13.1.0 version? It includes fix for this very annoying issue: https://github.com/getferdi/ferdi/issues/1269
https://www.electronjs.org/releases/stable?page=1#13.1.0

> Fixed pressing Alt+Shift and Alt+Ctrl toggling menu bar on KDE. #29443 (Also in 12, 14)

**Comment by vraravam** [comment]
@MurzNN - Ferdi is already on electron 13.1.4 - please use the nightlies from [here](http://github.com/vraravam/nightlies/releases)

**Comment by MurzNN** [comment]
Yeah, on Nightly-68 all works, thanks! I didn't see nightlies here https://github.com/getferdi/ferdi/releases/ so tested latest beta.

**Comment by avielc** [comment]
> @MurzNN - Ferdi is already on electron 13.1.4 - please use the nightlies from [here](https://github.com/vraravam/nightlies/releases)

Page not found mate.. what to do?

**Comment by vraravam** [comment]
@avielc - i had exposed the nightlies in my fork - while we were waiting for the signing keys. These have now been incorporated in the main CI toolchain. The nightlies can be found as per the `README.md` over [here](http://github.com/getferdi/nightlies/releases). HTH

**Comment by avielc** [comment]
Thanks, @vraravam looking it up now. 
I'm curious though if screen sharing works for various apps (mostly slack matters, as I use it most often. )

**Comment by vraravam** [comment]
Raised the following PRs for the release:
Ferdi website: 
homebrew cask: https://github.com/Homebrew/homebrew-cask/pull/108672
homebrew cask versions: https://github.com/Homebrew/homebrew-cask-versions/pull/11428

**Comment by vantezzen** [comment]
Thank you @vraravam, great work!

**Comment by vraravam** [comment]
@vantezzen - I am not sure how to go about fixing/finishing the two outstanding tasks: about the announcement API and scheduling tweets/instagram posts. Please help and mark those as done?

**Comment by vantezzen** [comment]
Announcement API would need to changed on the server - as I also wrote, I don't currently have access to that. Tweet is published, @kytwb might create a Canva image for instagram

**Comment by vraravam** [comment]
@kytwb - closing this issue since we have released 5.6.0 (but a couple of tasks are still open since we do not have context on what/how to do those).
