### ISSUE TITLE
Road to Ferdi v5.5.0 stable

### ISSUE THREAD

**Issue by vantezzen** [getferdi/ferdi#536]
It has been over two months since we've last released a release, so I think it's time that we prepare for the next one.
5.4.4 contains many important bugs fixes and features (e.g. fixing the internal server for Windows, fixing context menus and adding `user.js`) so we should now concentrate on getting small, remaining bugs out of Ferdi, especially testing Windows compatability.

I would also suggest that we release a pre-release "-gm" version (inspired by Apple's [Golden Master](https://www.theiphonewiki.com/wiki/Golden_Master) releases) for full releases from now on. We can then test this build before releasing the final version.

I don't think we can release an AppX version for the next release yet as I am currently having difficulties installing that on the Windows VM.

## Todo 5.5.0-gm
- [x] Update Changelog (hopefully automatic, as suggested)
- [x] Binary testing (with contributors)
- ~Schedule tweet~

## Todo 5.5.0
- [x] Update Changelog (hopefully automatic, as suggested)
- [x] Binary testing (hopefully also on a Windows VM)
- ~Staged roll out~
- [ ] Schedule tweet
- [x] Announcement API
- [x] Update cask, download links

**Comment by vantezzen** [comment]
I'd schedule the release of 5.4.4-gm to when #549 is merged

**Comment by kytwb** [comment]
@vantezzen Should we wait for https://github.com/getferdi/recipes/issues/91, https://github.com/getferdi/recipes/issues/59 and maybe another couple of quick wins we could get from the open recipes issues?

**Comment by kytwb** [comment]
Or should we go with 5.5.0-gm now and includes the recipes fixes in 5.5.0?

**Comment by kytwb** [comment]
WhatsApp is continuously reloading on this screen in 5.5.0-gm for me:

<img width="1047" alt="Screen Shot 2020-04-17 at 10 16 47 PM" src="https://user-images.githubusercontent.com/412895/79614764-22f64b80-80f9-11ea-8bd8-6bc32861af34.png">

Otherwise the Google services work properly.

**Comment by kytwb** [comment]
Slack icons are back:

<img width="342" alt="Screen Shot 2020-04-18 at 2 08 58 PM" src="https://user-images.githubusercontent.com/412895/79638663-9bebb680-817e-11ea-999b-c84b07ca8769.png">

**Comment by kytwb** [comment]
I can't seem to see the Dark Reader settings (https://github.com/getferdi/ferdi/issues/531). Other than that and the WhatsApp issue, it looks good to me.

**Comment by vantezzen** [comment]
> I can't seem to see the Dark Reader settings

You should be able to see it on the individual service settings screen (not Ferdi's global settings) after enabling dark mode there.

**Comment by kytwb** [comment]
I have only noted this regarding the Dark Reader settings:

<img width="411" alt="Screen Shot 2020-04-17 at 10 15 24 PM" src="https://user-images.githubusercontent.com/412895/79641421-64393a80-818f-11ea-8166-f4fdaed42d5d.png">

Should we try to update the WhatsApp recipe to use a custom user agent?

**Comment by vantezzen** [comment]
> Should we try to update the WhatsApp recipe to use a custom user agent?

Yes, sounds good

**Comment by kytwb** [comment]
📦 [v5.5.0-gm](https://github.com/getferdi/ferdi/releases/tag/v5.5.0-gm) is now available! You are welcome to give it a try and let us know of any regressions.  
We are already addressing the issues mentioned above for 5.5.0 🙏

**Comment by kytwb** [comment]
👀 Sentry errors related to v5.5.0-gm: https://sentry.io/organizations/ferdi-messenger/issues/?project=1803053&query=is%3Aunresolved+release%3AFerdi5.5.0-gm

**Comment by kytwb** [comment]
I think we are going to have a potential issue with the following recipes in v5.5.0-gm:

<img width="468" alt="Screen Shot 2020-04-19 at 10 04 18 AM" src="https://user-images.githubusercontent.com/412895/79685042-356da380-8225-11ea-9351-ebdfec3a2d40.png">

Potentially affected: Instagram, Discord, Jira, Kaizala, Messenger, **MSTeams**, Skype, Steam Chat, **WhatsApp**.

**Comment by kytwb** [comment]
@vantezzen How should we proceed to ship the latest fixes? Can we bump GM?

**Comment by vantezzen** [comment]
5.5.0-gm.2 ?

**Comment by Stanzilla** [comment]
pretty sure auto updates still don't work, so you'll have enough time to test with a small user base

**Comment by kytwb** [comment]
Let's release 5.5.0-gm.2 to include the latest fixes, then focus on fixing the auto-updater / recipes remote update for 5.5.0 stable? What do you think? I will be able to allocate some time to help push in that direction.

**Comment by vantezzen** [comment]
Sound good

**Comment by kytwb** [comment]
📦 Just published the [v5.5.0-gm.2](https://github.com/getferdi/ferdi/releases/tag/v5.5.0-gm.2) pre-release! Feedback welcome! 🙏

**Comment by kytwb** [comment]
The cheaper ones seem to be [Sectigo](https://sectigo.com/signing-certificates/code-signing) ($166/y) and [Comodo](https://www.comodo.com/landing/ssl-certificate/authenticode-signature/) ($179.95/y).

**Comment by kytwb** [comment]
I think it was a bit ambitious to try to fix the auto-updater and the remote recipe updates for 5.5.0. I will focus on releasing 5.5.0 as it for now as the last stable release (5.4.3) starts to be very old and contains a lot of bugs preventing usage of Google services and usage of Ferdi without an account on Windows. This is having a negative impact for people trying to install Ferdi from channels referencing only the last stable release.

We will iterate from there 🙏

**Comment by mahadevans87** [comment]
makes sense. Thank you for the update

**Comment by kytwb** [comment]
Updated the changelog and tested the binaries on macOS/Windows (using [Parallels Desktop](https://github.com/getferdi/ferdi/issues/415#issuecomment-618880582) for Windows on macOS):

<img width="1347" alt="Screen Shot 2020-04-26 at 9 22 06 PM" src="https://user-images.githubusercontent.com/412895/80320586-c553b480-8806-11ea-87db-76ffa0abcd7d.png">


And published the [v5.5.0](https://github.com/getferdi/ferdi/releases/tag/v5.5.0) release (following this [release workflow](https://github.com/getferdi/ferdi/pull/641#issuecomment-619375895)) 🥳 I experienced an issue with the tagging, as I targeted the wrong branch when creating the draft release:

<img width="464" alt="Screen Shot 2020-04-26 at 9 31 40 PM" src="https://user-images.githubusercontent.com/412895/80320346-70fc0500-8805-11ea-9835-6e4b2f4f8511.png">

I think I should have targeted the `master` branch, squash merge `release` into `master` and publish the release so the latest commit of `master` gets tagged.

<img width="785" alt="Screen Shot 2020-04-26 at 9 34 26 PM" src="https://user-images.githubusercontent.com/412895/80320402-b6203700-8805-11ea-85db-448f19a1aca6.png">

I also experienced an issue with Windows signing (see [this build](https://ci.appveyor.com/project/kytwb/ferdi/builds/32452787)) but fixed it with the following from [electron.build docs](https://ci.appveyor.com/project/kytwb/ferdi/builds/32452787):

> Keep in mind that Windows is not able to handle environment variable values longer than 8192 characters, thus if the base64 representation of your certificate exceeds that limit, try re-exporting the certificate without including all the certificates in the certification path (they are not necessary, but the Certificate Manager export wizard ticks the option by default), otherwise the encoded value will be truncated.

Updated the [download links on the website](https://getferdi.com/download/) via https://github.com/getferdi/website/commit/c60870ebdf16bf0a5dc364ce1222f8aa54cccfe7 and the cask via https://github.com/Homebrew/homebrew-cask/pull/81409.

**Comment by kytwb** [comment]
Updated the checklist in the original post. I am not sure how the announcement API works exactly, but it would be nice to make use of it to communicate with other users on the current state of things. I will prepare and schedule some announcement tweets 🙏

**Comment by kytwb** [comment]
Something slipped through with macOS notarization (notarization was triggered on tag build only), fixed it and re-releasing.

**Comment by kytwb** [comment]
Also, I think the issue with re-using the `release` branch is that we can't keep a clear history of the iterations made on it; or at least it would be clearer with versioned releases branch (`release/v5.5.0`). Right now I did some fixes on the release branch and squash merged into master, but by reading the release branch history we will not be able to determinate what got squash merged for which release. We can iterate on this for the next release.

**Comment by kytwb** [comment]
📦 Re-shipped [v5.5.0](https://github.com/getferdi/ferdi/releases/tag/v5.5.0) and opened a new issue to iterate with the lessons learned during this iteration.

**Comment by kytwb** [comment]
I had to re-ship with the updated recipes. I will go on with https://github.com/getferdi/ferdi/issues/652 next to consolidate and automate, this should avoid us further mistakes and manual labor.

**Comment by kytwb** [comment]
Announcement API usage preview:

<img width="1552" alt="Screen Shot 2020-04-30 at 6 31 14 PM" src="https://user-images.githubusercontent.com/412895/80749510-0fde7500-8b16-11ea-9547-30e4d41e3d66.png">

The line height or rendering of the features listing seems a bit off, maybe we can get this better next iteration 🙏

**Comment by kytwb** [comment]
First iteration for a Twitter announcement image (using Canva; search for Twitter Posts for templates, customize using branding color palette):

<img width="1435" alt="Screen Shot 2020-04-30 at 2 20 02 PM" src="https://user-images.githubusercontent.com/412895/80749691-5d5ae200-8b16-11ea-8cde-366cc6dd2891.png">

**Comment by kytwb** [comment]
We iterated on the announcement tweet with @vantezzen:

<img width="631" alt="Screen Shot 2020-05-01 at 4 48 07 PM" src="https://user-images.githubusercontent.com/412895/80838837-6ff21b80-8be9-11ea-80d0-2789499746a7.png">

Final version: https://twitter.com/getferdi/status/1256262606295306241

<img width="640" alt="Screen Shot 2020-05-01 at 8 22 38 PM" src="https://user-images.githubusercontent.com/412895/80838870-8304eb80-8be9-11ea-873f-facfda1ab0c8.png">

**Comment by kytwb** [comment]
Congratulations everyone for this iteration! 🥳
